### ISSUE TITLE
submodule discount C lib in and compile as part of module

### ISSUE THREAD

**Issue by visnup** [tj/node-discount#10]
this is going to be controversial, but I wanted to bring it up. it would be interesting if the [discount C source](https://github.com/Orc/discount) were submoduled in this library and compiled as part of the module.

pros:
- it would make install more seamless
- it would allow more control over what discount code/version is used
- it's been done before: [rdiscount](https://github.com/rtomayko/rdiscount)

cons:
- it's a lot more work
- it makes discount compilation issues your issues too

**Comment by tj** [comment]
I'd be fine with it, I dont have time at the moment but other than that it should be ok :D

**Comment by visnup** [comment]
I'll try to work on this soon and send you a pull.

**Comment by visnup** [comment]
oh yeah, done.
