### ISSUE TITLE
Spits out random jitter after markdown block in jade

### ISSUE THREAD

**Issue by seidtgeist** [tj/node-discount#4]
Not sure whether it’s a jade or a node-discount bug.

It happens when I put a markdown filter into a jade file and refresh a lot:
I sometimes get random text snippets from other parts of the app inserted after filter.

Maybe I’m doing something wrong but I can’t imagine what exactly. The :markdown is inside a partial in a list of partials that’s being rendered via an each loop.

**Comment by dpritchett** [comment]
Same here, not using jade at all.

```
daniel@lucid:~/myapps/node_tests$ node
> var md = require('markdown')
> md.parse('markdown is *awesome*')
'<p>markdown is <em>awesome</em></p>\bI\u001a'
> md.parse('markdown is *awesome*')
'<p>markdown is <em>awesome</em></p>\bï¿½\u0019'
> md.parse('markdown is *awesome*')
'<p>markdown is <em>awesome</em></p>\bï¿½\u0019'
> md.parse('markdown is *awesome*')
'<p>markdown is <em>awesome</em></p>\bï¿½\u0019'
```

Node 0.3.0-pre, md 0.1.2.  Ubuntu 10.04.

**Comment by bpierre** [comment]
Same for me on OS X, it puts some random text at the end.

It seems to be related to unicode characters, like `’`

**Comment by seidtgeist** [comment]
So it’s probably related to splice/length expecting only ASCII chars in a string?

**Comment by dce** [comment]
I put a fix together for this (http://github.com/visionmedia/node-discount/issues/closed#issue/5) based on code in RDiscount, but my pull request hasn't been accepted.

**Comment by aeosynth** [comment]
This is a bug in discount - https://github.com/Orc/discount/issues#issue/14

edit - [this commit](https://github.com/Orc/discount/commit/968902742c1797868d75c05e703e2ca7fedac902) makes sure mkd_document creates a null-terminated buffer.
